//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1920543nazmi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class nazmidbEntities : DbContext
    {
        public nazmidbEntities()
            : base("name=nazmidbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CappadociaContent> CappadociaContents { get; set; }
        public virtual DbSet<Picture> Pictures { get; set; }
        public virtual DbSet<Slider> Sliders { get; set; }
    }
}
