//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1920543nazmi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slider
    {
        public int SliID { get; set; }
        public string SliderWay { get; set; }
    }
}
